/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.ClassNotFoundException;

/**
 *
 * @author carlosLopezAmaztalli
 */
public class frmDatos extends javax.swing.JFrame {
        Conexion cc=new Conexion();
        Connection cn=cc.getConnecction();
    private DefaultTableModel modelo;
    int contador=0;
    /**
     * Creates new form frmDatos
     */
    public frmDatos() {
        initComponents();
        CargarInterfaz();
        CargarDatos();
        this.setTitle("Formulario Datos de farmacia");
    }
    public void CargarInterfaz(){
        String datos [] [] [] []={};
        String columna[]={"Nombreproducto","Tipoproducto","Cantidadproducto","Nombreproveedor","Sucursal"};
        modelo=new DefaultTableModel(datos,columna);
        tablaDatos.setModel(modelo);
    }
    public void CargarDatos(){
        Producto p;
        for(int i=0;i<Ventanaprincipal.contenedor.size();i++){
            p=(Producto)Ventanaprincipal.contenedor.get(i);
            modelo.insertRow(contador, new Object[]{});
            modelo.setValueAt(p.getNombredelproducto(), contador, 0);
            modelo.setValueAt(p.getTipodelproducto(), contador, 1);
            modelo.setValueAt(p.getCantidaddelproducto(), contador, 2);
            modelo.setValueAt(p.getNombredelproveedor(), contador, 3);
            modelo.setValueAt(p.getSucursal(), contador, 4);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datos Registrados");

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del producto", "Tipo del producto", "Cantidad de producto", "Nombre del proveedor", "Sucursal"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        jButton1.setText("Cancelar el pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton1)
                .addGap(103, 103, 103)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(506, 506, 506))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try
        {
            for(int i=0;i<tablaDatos.getRowCount();i++)
            {
               
                    PreparedStatement pst=cn.prepareStatement("INSERT INTO farmacia(Nombreproducto,Tipoproducto,Cantidadproducto,Nombreproveedor,Sucursal) VALUES(?,?,?,?,?)");
                    pst.setString(1, tablaDatos.getValueAt(i, 0).toString());
                    pst.setString(2, tablaDatos.getValueAt(i, 1).toString());
                    pst.setString(3, tablaDatos.getValueAt(i, 2).toString());
                    pst.setString(4, tablaDatos.getValueAt(i, 3).toString());
                    pst.setString(5, tablaDatos.getValueAt(i, 4).toString());
                    pst.executeUpdate();  
            }
             }catch(Exception e){
                    System.out.print(e.getMessage());
                    }
       JOptionPane.showMessageDialog(this,"ENVIANDO EL PRODUCTO......");
       Tabladebasededatos mostrar=new Tabladebasededatos();
            mostrar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(this, "¿Esta seguro de cancelar el pedido?, los datos se borraran");
        if(respuesta==JOptionPane.YES_OPTION){
        int elitotal=tablaDatos.getRowCount();
        for(int i=elitotal-1;i>=0;i--){
            modelo.removeRow(i);
        }
        JOptionPane.showMessageDialog(this, "Operacion exitosa");
        this.dispose();
      }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
